# Generated by Django 2.2.16 on 2022-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220906_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultPassword123', max_length=100),
        ),
    ]
