# Generated by Django 2.2.16 on 2022-09-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220907_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmcode',
            old_name='code',
            new_name='confirmation_code',
        ),
    ]
