# Generated by Django 2.2.16 on 2022-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220907_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
